User Sign Up/Profile Flow
mrao2/newtowndogs pull request #39
Opened 2023-08-14 03:50 UTC by emjayholla

- Create account is functioning. 
- User profile fields are now editable and will save in the database. 
- SQL files have been changed, *be sure to drop the user_profile table and re-run it*

2023-08-14 16:12 UTC, LaplacesAngel reviewed
For some reason can't get the submit button to work after hitting signup:
![image](https://github.com/mrao2/newtowndogs/assets/118093209/4d43cebf-ef80-4221-a6b0-850a2ed589f4)


Also not able to load the profile page:
![image](https://github.com/mrao2/newtowndogs/assets/118093209/bc2c3128-53f9-4b4c-bae4-a90d2711edeb)


Not sure if it's just me or not, maybe someone else could take a look? 
Or Maggie are there potentially changes on your local branch that haven't been pushed up yet if it's working for you?

2023-08-14 21:44 UTC, Dalton-Kujawa commented
Hey Maggie I could create a user through sign up but is the profile page support to work at all? its crashing the back end due to some table joining issues.

2023-08-16 19:42 UTC, Dalton-Kujawa requested changes
Hey Maggie, things are working well and look good on both pages. I have to request changes only because both sign up and profile need some changes before we can commit them into main. They both need error handling on screen. As it is right now if a user puts in a field that isnt allowed (aka. A phone number thats already used, or a putting in Texas instead of TX, or using too many characters for some names) it will crash the backend. I think just a little bit of verification on the front end input should fix that right up! Also in .vscode/settings.json you have eslint.enable set to false. This would get rid of all those nice red squiggles that tell use when we are making mistakes in our code. ( although they can be annoying)

2023-08-17 22:59 UTC, Dalton-Kujawa commented on backend/data/db.json
> +{
I have no idea where this file came from lol this is from my original push weeks ago!

2023-08-19 16:19 UTC, Dalton-Kujawa approved these changes
![BackendErrorCrash](https://github.com/mrao2/newtowndogs/assets/125609395/8acdf4eb-8d3b-4516-9af8-c7175b1dd2e4)
I am going to approve the code but I did get a backend crash for some of the inputs on profile. If you can make sure you pull from main before you Merge the branch in and make sure you dont have any conflicts! Thanks!

2023-08-19 19:10 UTC, merged